// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: npm run generate-routes
// Generated at: 2025-07-27T20:07:21.142Z

export default [
  '/',
  '/blog/hello-world',
  '/blog/lets-build',
  '/blog/practical-dependency-inversion-principle',
  '/blog/circular-dependencies',
  '/blog/ultimate-testing-guideline',
  '/blog/let-go'
];
