// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: npm run generate-routes
// Generated at: 2025-07-27T20:19:20.107Z
// Source: API

export default [
  '/',
  '/blog/let-go',
  '/blog/ultimate-testing-guideline',
  '/blog/circular-dependencies',
  '/blog/practical-dependency-inversion-principle',
  '/blog/lets-build',
  '/blog/hello-world'
];
