#!/usr/bin/env node

/**
 * Dynamic route generator for blog posts
 * Reads markdown files and generates routes for prerendering
 */

const fs = require('fs');
const path = require('path');

// Path to the blog posts directory
const POSTS_DIR = path.join(__dirname, '../../blog-api/posts');
const OUTPUT_FILE = path.join(__dirname, '../src/app/prerender-routes.ts');

/**
 * Extract title from markdown frontmatter
 */
function extractTitleFromMarkdown(content) {
  const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
  if (!frontmatterMatch) return null;
  
  const frontmatter = frontmatterMatch[1];
  const titleMatch = frontmatter.match(/^title:\s*(.+)$/m);
  return titleMatch ? titleMatch[1].trim() : null;
}

/**
 * Convert title to URL-friendly anchor
 */
function titleToAnchor(title) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '') // Remove special characters
    .replace(/\s+/g, '-') // Replace spaces with hyphens
    .replace(/-+/g, '-') // Replace multiple hyphens with single
    .replace(/^-|-$/g, ''); // Remove leading/trailing hyphens
}

/**
 * Generate routes from markdown files
 */
function generateRoutes() {
  console.log('🔄 Generating prerender routes from blog posts...');
  
  if (!fs.existsSync(POSTS_DIR)) {
    console.error(`❌ Posts directory not found: ${POSTS_DIR}`);
    process.exit(1);
  }

  const routes = ['/'];
  const files = fs.readdirSync(POSTS_DIR);
  
  for (const file of files) {
    if (!file.endsWith('.md')) continue;
    
    const filePath = path.join(POSTS_DIR, file);
    const content = fs.readFileSync(filePath, 'utf8');
    const title = extractTitleFromMarkdown(content);
    
    if (title) {
      const anchor = titleToAnchor(title);
      const route = `/blog/${anchor}`;
      routes.push(route);
      console.log(`✅ Found post: "${title}" -> ${route}`);
    } else {
      console.warn(`⚠️  No title found in ${file}`);
    }
  }

  // Generate simple routes file for Angular prerender
  const routesList = routes.map(route => `'${route}'`).join(',\n  ');
  const tsContent = `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: npm run generate-routes
// Generated at: ${new Date().toISOString()}

export default [
  ${routesList}
];
`;

  fs.writeFileSync(OUTPUT_FILE, tsContent);
  console.log(`✅ Generated ${routes.length} routes in ${OUTPUT_FILE}`);
  console.log('📦 Routes:', routes);
}

// Run the generator
generateRoutes();